In [29]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

from PIL import Image
import cv2
import numpy as np
import tensorflow.keras as keras
import tensorflow as tf
import matplotlib.pyplot as plt

# model = keras.models.load_model("Mobilefacenet-TF2-coral_tpu/model/model_with_mask_clf.h5")
model = keras.models.load_model("Mobilefacenet-TF2-coral_tpu/pretrained_model/training_model/inference_model_0.993.h5")
resize = tf.keras.layers.Resizing(
    112,
    96,
    interpolation='bilinear',
)
model.summary()



Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 112, 96, 3)  0           []                               
                                ]                                                                 
                                                                                                  
 zero_padding2d (ZeroPadding2D)  (None, 114, 98, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv2d (Conv2D)                (None, 56, 48, 64)   1728        ['zero_padding2d[0][0]']         
                                                                                                  
 batch_normalization (BatchNorm  (None, 56, 48, 64)  256         ['conv2d[0][0]']             

In [30]:
def preprocess(img):
    # img = cv2.resize(img, (96, 112))
    size = img.shape
    # print(size)
    img = resize(tf.convert_to_tensor(img))
    img = (img - 127.5) / 128.0
    img = np.expand_dims(img, axis=0)
    return img



In [31]:
from PIL import Image
im = Image.fromarray(cv2.resize(plt.imread('img.jpg'), (96, 112)))
im.save("resized.jpg")

In [32]:
preprocess(plt.imread('resized.jpg'))

array([[[[ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         ...,
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375]],

        [[ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         ...,
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375]],

        [[ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         ...,
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375]],

        ...,

        [[ 0.99609375,  0.98828125,  0

In [33]:
def euclidean_dist(x1, x2):
    return np.linalg.norm(x1 - x2)

img = preprocess(plt.imread('img.jpg'))
a = model(tf.convert_to_tensor(img))
a

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[-3.3994482 , -3.2185779 ,  1.5478685 ,  1.1064566 , -0.16630504,
         1.3889586 , -0.62219405, -1.5233731 , -0.302846  , -1.9582496 ,
        -0.44434988,  1.5259433 ,  1.2686039 ,  0.4393974 , -1.1110581 ,
         0.9936357 , -0.8260415 ,  0.19120562, -1.6863995 ,  0.67737556,
        -2.8289006 ,  1.9382775 ,  3.644413  , -2.2278416 ,  0.5901638 ,
         0.9218455 ,  0.7949065 ,  0.7012178 ,  0.94555616, -0.34038657,
        -0.64387655,  2.2898507 ,  0.8841664 ,  3.3135328 ,  0.39789206,
        -2.7895563 ,  1.321036  ,  1.045691  , -0.81716394,  0.13203722,
         0.50785494,  4.1255455 ,  1.9610745 ,  3.9598432 ,  1.110459  ,
         2.187032  ,  0.65102166,  0.5095916 ,  2.0405974 , -0.48315966,
        -1.5324838 , -1.1458629 , -0.63590306, -1.7259353 , -4.882137  ,
        -3.4097521 , -2.9723308 ,  0.4076898 , -1.4435862 ,  0.09437474,
         0.31009036, -0.86705434,  0.8890971 , -1.6296439 ,  1.8939967 ,
 

In [35]:
b = [-3.363057, -3.3670115, 1.6185024, 1.0930127, -0.16038689, 1.4107054, -0.6266763, -1.5281563, -0.324163, -1.9759235, -0.47354716, 1.510524, 1.2404579, 0.4429078, -1.073968, 0.9732202, -0.8749176, 0.19761337, -1.7729862, 0.7475232, -2.8874774, 1.9225782, 3.6506002, -2.2822838, 0.4724352, 0.91275346, 0.84922844, 0.6687087, 0.9111854, -0.3401779, -0.62995607, 2.3192737, 0.83848673, 3.3520093, 0.46050256, -2.8001895, 1.2794263, 1.051071, -0.8146802, 0.16394417, 0.48726934, 4.1252437, 1.9188931, 4.007771, 1.0777833, 2.225208, 0.7278501, 0.5229095, 2.0582707, -0.53748524, -1.6093235, -1.220011, -0.67237127, -1.701094, -4.9245634, -3.412837, -2.9208953, 0.41692644, -1.4343562, 0.15541574, 0.2979197, -0.8659953, 0.86486787, -1.6601696, 1.9702702, 2.4104788, 2.0239358, 0.13490054, -1.7985483, -2.4082885, -3.6248763, -2.3266015, 1.0891794, 0.23187575, -0.6585653, 1.1588187, -1.0286479, 2.8411863, 3.9672885, -2.2327142, 1.0507414, 1.4070841, 0.0812722, 3.3821626, -2.1251082, 1.7355876, -2.7017007, -1.6643523, 0.091069534, 3.414928, -2.727612, -0.6302599, 3.0545325, -0.99895406, -1.4832839, -1.6075903, -3.7117615, 1.9550216, -3.3576336, -3.6037142, 2.7580075, -1.0723448, 1.6304343, 3.134347, -0.76097435, 2.9281552, -1.9363056, -3.6004403, -1.114956, 2.138711, 1.7705407, 0.46488452, 1.0999652, 2.098936, -1.5314828, -2.7643638, -0.18233809, 0.41318446, -2.7342544, 1.36619, 0.7080603, 2.0771651, 1.650764, 0.5179871, -4.3808813, 3.688143, 0.42904085, 0.2856686]

euclidean_dist(a,b)

0.47060135

In [40]:
model = tf.saved_model.load("saved_models/tf/DW_seesawFaceNetv2.pb")
resize = tf.keras.layers.Resizing(
    112,
    112,
    interpolation='bilinear',
)


In [41]:
def preprocess(img):
    # img = cv2.resize(img, (96, 112))
    size = img.shape
    # print(size)
    img = resize(tf.convert_to_tensor(img))
    img = img/255.
    img = np.expand_dims(img, axis=0)
    return img


In [54]:
img = preprocess(plt.imread('img.jpg'))
a = model(tensor=tf.transpose(tf.convert_to_tensor(img), [0, 3, 1, 2]))
a

{'2882': <tf.Tensor: shape=(1, 512), dtype=float32, numpy=
 array([[ 6.54684263e-05, -4.97061238e-02,  1.01208188e-01,
         -7.08802491e-02,  3.30184735e-02, -1.94119792e-02,
          8.64591170e-03, -4.21898179e-02, -2.37236824e-03,
          8.50073807e-03,  6.38914257e-02, -3.09384544e-03,
          5.23955887e-03,  6.88255578e-02,  1.77454408e-02,
          1.39238534e-03, -5.71095124e-02,  5.80022335e-02,
          1.42321503e-02, -4.12097499e-02,  3.89000364e-02,
         -4.14501317e-03,  6.98218644e-02,  1.04182977e-02,
          8.20805412e-03, -5.87513000e-02, -2.48999745e-02,
          5.75409562e-04, -4.13688198e-02, -4.41616401e-02,
         -8.37161299e-03, -4.84556658e-03, -2.21711267e-02,
          8.69522896e-03,  6.83704857e-03,  2.71118358e-02,
         -1.54895624e-02,  1.23811085e-02,  1.08293938e-02,
          9.02488157e-02,  3.44342180e-02,  5.38904294e-02,
         -1.92849655e-02, -1.08712595e-02,  3.10560036e-03,
         -3.44358645e-02,  1.39429256e-01