In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

from PIL import Image
import cv2
import numpy as np
import tensorflow.keras as keras
import tensorflow as tf
import matplotlib.pyplot as plt

# model = keras.models.load_model("Mobilefacenet-TF2-coral_tpu/model/model_with_mask_clf.h5")
model = keras.models.load_model("Mobilefacenet-TF2-coral_tpu/pretrained_model/training_model/inference_model_0.993.h5")

model.summary()

def preprocess(img):
    img = cv2.resize(img, (96, 112))
    img = (img.astype('float32') - 127.5) / 128.0
    img = np.expand_dims(img, axis=0)
    return img



Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 112, 96, 3)  0           []                               
                                ]                                                                 
                                                                                                  
 zero_padding2d (ZeroPadding2D)  (None, 114, 98, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv2d (Conv2D)                (None, 56, 48, 64)   1728        ['zero_padding2d[0][0]']         
                                                                                                  
 batch_normalization (BatchNorm  (None, 56, 48, 64)  256         ['conv2d[0][0]']             

In [5]:
preprocess(plt.imread('img.jpg'))

array([[[[ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         ...,
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375]],

        [[ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         ...,
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375]],

        [[ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         ...,
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375],
         [ 0.99609375,  0.99609375,  0.99609375]],

        ...,

        [[ 0.99609375,  0.99609375,  0

In [3]:
def euclidean_dist(x1, x2):
    return np.linalg.norm(x1 - x2)

img = preprocess(plt.imread('img.jpg'))
model(tf.convert_to_tensor(img))

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[-3.3953145 , -3.1781116 ,  1.5912389 ,  1.1074966 , -0.1729312 ,
         1.3882215 , -0.6250953 , -1.5293707 , -0.2924978 , -1.9561177 ,
        -0.43223834,  1.5298215 ,  1.274619  ,  0.4491017 , -1.0990691 ,
         1.0145894 , -0.8258563 ,  0.18062103, -1.6740481 ,  0.67545784,
        -2.7952044 ,  1.9380286 ,  3.6624036 , -2.2356505 ,  0.57901573,
         0.94637096,  0.7991063 ,  0.7004314 ,  0.9313083 , -0.31679612,
        -0.6568145 ,  2.2907884 ,  0.8818123 ,  3.3073409 ,  0.40262103,
        -2.7652366 ,  1.3305466 ,  1.0380416 , -0.8255025 ,  0.1200327 ,
         0.51987356,  4.1294127 ,  1.939705  ,  3.961227  ,  1.1261883 ,
         2.1781178 ,  0.6482663 ,  0.5210828 ,  2.0379887 , -0.48424792,
        -1.5298147 , -1.1449115 , -0.6280158 , -1.7067404 , -4.856948  ,
        -3.3892634 , -2.9712334 ,  0.39065915, -1.4593638 ,  0.09434405,
         0.3071493 , -0.84150726,  0.90463185, -1.6185391 ,  1.8940423 ,
 